### ISSUE TITLE
Split up the twitter-api-spec.yml file

### ISSUE THREAD

**Issue by Silind** [Silind/twitter-api-client#15]
### Currently
The Twitter API Client is generated based on one single `twitter-api-spec.yml` file which is currently a whopping 3000+ lines long.
It's really cumbersome to scroll around in that file to find what you want.

### Desired
The `twitter-api-spec.yml` file is split up into multiple `.yml` files.
One for each group.

### AC
- The folder `src/spec/` is renamed to `src/specs/` and all references in the generator files are changed.
- The file `twitter-api-spec.yml` is split up into multiple files.  

### Additional notes
To begin with, I think it would be great to have one for each group.  
A file `src/specs/basics.yml`, a file `src/specs/accounts-and-users.yml`, a file `src/specs/tweets.yml`, etc.  
The file `twitter-api-spec.yml` should still be the main spec file that references these other files.

**Comment by Silind** [comment]
This task is up for grabs during Hacktoberfest :raised_hands:

If you want to work on this task, please claim it here in the comments.
Feel free to ask any questions here as well :blush:

**Comment by DipanjanDasIT** [comment]
I am wiling to work on this.

**Comment by Silind** [comment]
Hi @DipanjanDasIT
That sounds awesome! I'll assign you right away :smile:

**Comment by DipanjanDasIT** [comment]
@Silind can we change the spec file format from yaml to RAML?

**Comment by iliran11** [comment]
Can you please stick to YAML format?

**Comment by Silind** [comment]
Yes, let's stick to YAML format.
The change will be too comprehensive at this moment.
