### ISSUE TITLE
Standard search API is not available for usage

### ISSUE THREAD

**Issue by iliran11** [Silind/twitter-api-client#23]
I cannot use this resource `https://api.twitter.com/1.1/search/tweets.json`.
the URL [appear in `twitter-api-spec.yml`](https://github.com/Silind/twitter-api-client/blob/3c39be655c5af5b44b6bc404791f5cf479052820/src/spec/twitter-api-spec.yml#L2856) but doesn't translate into the references or any of the clients.

Am I wrong?

**Comment by Silind** [comment]
No, you're right! Nice catch.
I opened a PR for this. Waiting for your review :slightly_smiling_face:

**Comment by Silind** [comment]
Fixed in v. 1.0.4
