### ISSUE TITLE
Support DELETE verb

### ISSUE THREAD

**Issue by Silind** [Silind/twitter-api-client#24]
Currently, only `GET` and `POST` are supported.
There is one endpoint using the `DELETE` verb.
[See here](https://github.com/Silind/twitter-api-client/blob/master/src/spec/twitter-api-spec.yml#L2982)

The endpoint gets bypassed and the client is not created.
[See here](https://github.com/Silind/twitter-api-client/blob/master/src/generator/writeClients.ts#L29)

#### AC
- Support calling the Twitter API with the `DELETE` verb.
- Create a corresponding client from the spec file.

**Comment by iliran11** [comment]
Hi @Silind 
Did you mean to point [here](https://github.com/Silind/twitter-api-client/blob/master/src/spec/twitter-api-spec.yml#L2982) as the only DELETE endpoint? 

Your first link points to ```Search Tweets``` ... Is it just a mistake or am I missing something?

**Comment by Silind** [comment]
Yes, good point @iliran11.
The spec file has been updated since this issue was created, so it's pointing to the wrong line now.
I'll fix it right away :smile:

**Comment by iliran11** [comment]
So I'll take this task if that's OK with you :)

**Comment by Silind** [comment]
Sounds great :raised_hands:

**Comment by Silind** [comment]
Included in v. 1.1.0
