### ISSUE TITLE
Support for OAuth 2.0 Bearer Token

### ISSUE THREAD

**Issue by OhNiice** [Silind/twitter-api-client#8]
Could you consider adding support for OAuth 2.0 Bearer Token?

My use case is exactly the one presented in [Twitter's doc](https://developer.twitter.com/en/docs/authentication/oauth-2-0) in which I only need read-only access to pull public information.

Thank you for providing this library.

**Comment by Silind** [comment]
Hi, @OhNiice 
Thanks for creating this issue.

Yes, for sure.
I'll make sure to look back at this :blush:

**Comment by Silind** [comment]
Support for OAuth 2 is now included.
Take a look at the reference here:
https://github.com/Silind/twitter-api-client/blob/master/REFERENCES.md#twitterclientbasicsoauth2tokenparameters
